### ISSUE TITLE
New SO Profile Page prevents adding new users

### ISSUE THREAD

**Issue by Plutonix** [blunderboy/stackeye#39] opened 2015-05-19 14:36 UTC
With the recent revision to the SO user profile page, the "FOLLOW" button to add a User no longer displays.  The result is that there is no way to add new users.

It may be that the layout changed radically or that the new tabs (Profile | Activity | Edit...) overlay or are in the space previously used for the Follow button.

**Comment by blunderboy** [comment] 2015-05-19 14:44
@Plutonix Thanks for opening the issue. I see the issue now. Actually, StackEye tries to insert Follow button before a selector. Most likely, the issue is since the webpage is changed, content script is not able to find that element and therefore it is not able to place follow button anywhere..

I can work on it but if you want feel free to generate pull request for this issue.
I will be more than happy to review it :)

**Comment by blunderboy** [comment] 2015-05-25 05:04
@Plutonix Can you give me the URL where you are not able to find the "Follow" button. I can see there are 2 tabs on each profile page:
1. http://stackoverflow.com/users/816213/blunderboy?tab=profile
2. http://stackoverflow.com/users/816213/blunderboy?tab=activity

So, If you go to profile tab, you should be able to see the "Follow" button there. I will go ahead and fix the issue for activity tab.

Just let me know if we are on the same page.

cc: @rahuljain983

**Comment by Plutonix** [comment] 2015-06-03 21:29
Here is what I see for your profile tab: http://i.imgur.com/Iy3kbjy.jpg

**Comment by blunderboy** [comment] 2015-06-04 04:34
![stackeye_39](https://cloud.githubusercontent.com/assets/3108399/7976933/db9d7408-0aa0-11e5-8c95-d0bd2e3b15b6.png)

Here is what I see on another user profile. Now it is interesting.
Please tell me your browser info and I will reproduce it.

**Comment by Plutonix** [comment] 2015-06-04 12:35
Sorry, I meant to include browser info but could no find a way to edit the comment/entry. Chrome Version 43.0.2357.81 m.  I loaded Skeet profile to be sure and the button is not there.

**Comment by Plutonix** [comment] 2015-06-04 15:29
Fixed.  I checked the StackEye version and I was using 2.2.1, installing the latest fixed the issue (though I lost all the things I was already watching).  I thought I had checked for an update when they first revised the pages, but I guess not.

**Comment by blunderboy** [comment] 2015-06-04 15:54
@Plutonix I was about to ask you the same thing to provide me the version you are having on chrome://extensions page. 

StackEye stores the data in Chrome local storage so you should not lose your data unless you clear your local storage somehow. Do you remember if you cleared your local storage data ?

**Comment by Plutonix** [comment] 2015-06-04 18:37
In the Chrome store, it said "installed" even though the version was wrong, and I could not see a way to update so I deleted the old one to install the new one. Its not a big deal.  Thanks.

**Comment by blunderboy** [comment] 2015-06-05 03:54
@Plutonix Appreciate your feedback. Can you rate it on Chrome Store [0] ? When I developed StackEye I thought it would be enjoyed by most of SO users but id did not gain much love So I have paused development on it for a while but I have certain plans to add more features into it.

[0]: https://chrome.google.com/webstore/detail/stackeye/pihfndpmcafdecheofkjfkadecoogigm/reviews?hl=en

**Comment by Wakeupbuddy** [comment] 2015-06-11 21:23
Hi, it seems the new SO profile in http://cstheory.stackexchange.com and mathoverflow.com also broke the "Follow" button? Is this the same issue discussed in this thread?

**Comment by blunderboy** [comment] 2015-06-12 03:53
@Wakeupbuddy Gotcha..These pages are still on old stackoverflow profile page design. I updated my code to show follow button as per on new profile page design. I will look into this on priority now. Thanks for reporting this

**Comment by blunderboy** [comment] 2015-06-15 01:12
This issue has  been fixed and should be available in latest release of StackEye v 2.3.1. Closing this.
Thanks @Plutonix and @Wakeupbuddy for opening this and making StackEye one step better.

**Closed by blunderboy** 2015-06-15 01:12 UTC
Labels: bug
